#!/usr/bin/env python3
"""
Script to import JSON gear data files into the database.
Reads all JSON files from data/bis_by_class/s5/ and generates SQL INSERT statements.
"""

import os
import json
import sys
from pathlib import Path

def escape_sql_string(s):
    """Escape single quotes and backslashes for SQL"""
    return s.replace("\\", "\\\\").replace("'", "''")

def generate_sql_inserts(base_path):
    """Generate SQL INSERT statements for all JSON files"""
    sql_statements = []
    
    # Path to bis_by_class directory
    bis_path = Path(base_path) / "data" / "bis_by_class" / "s5"
    
    if not bis_path.exists():
        print(f"Error: Directory {bis_path} does not exist")
        return []
    
    # Iterate through all class directories
    for class_dir in sorted(bis_path.iterdir()):
        if not class_dir.is_dir():
            continue
        
        class_name = class_dir.name
        
        # Iterate through all JSON files in the class directory
        for json_file in sorted(class_dir.glob("*.json")):
            specialization = json_file.stem  # filename without .json
            
            try:
                # Read and parse JSON file
                with open(json_file, 'r', encoding='utf-8') as f:
                    json_data = json.load(f)
                
                # Convert back to JSON string (minified)
                json_str = json.dumps(json_data, separators=(',', ':'))
                
                # Escape for SQL
                json_str_escaped = escape_sql_string(json_str)
                
                # Generate INSERT statement
                sql = f"INSERT INTO `gvg_gear_data` (`season`, `class_name`, `specialization`, `json_data`) VALUES ('s5', '{class_name}', '{specialization}', '{json_str_escaped}') ON DUPLICATE KEY UPDATE `json_data` = VALUES(`json_data`);"
                sql_statements.append(sql)
                
                print(f"Processed: {class_name}/{specialization}.json")
                
            except Exception as e:
                print(f"Error processing {json_file}: {e}", file=sys.stderr)
                continue
    
    return sql_statements

def main():
    # Get the script directory (modules/mod-gvg-gear-manager)
    script_dir = Path(__file__).parent.parent
    
    # Generate SQL statements
    sql_statements = generate_sql_inserts(script_dir)
    
    if not sql_statements:
        print("No SQL statements generated")
        return 1
    
    # Write to output file
    output_file = script_dir / "data" / "sql" / "db-world" / "gvg_gear_manager_data_insert.sql"
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write("-- GvG Gear Manager Module - Gear Data Insert\n")
        f.write("-- This file is auto-generated by import_gear_data.py\n")
        f.write("-- DO NOT EDIT MANUALLY\n\n")
        for sql in sql_statements:
            f.write(sql + "\n")
    
    print(f"\nGenerated {len(sql_statements)} INSERT statements")
    print(f"Output file: {output_file}")
    return 0

if __name__ == "__main__":
    sys.exit(main())

